### ISSUE TITLE
Allow configurable mapping of pins to control SPI

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/clibspi#5]
This is required by:
https://github.com/iqrfsdk/iqrf-daemon/issues/80

**Comment by spinarr** [comment]
Offer init function for mapping GPIO (mainly SPI links and ENABLE) so that it can be used for
configuration by the SW using clibspi.

**Comment by fmikulu** [comment]
Ideas to consider by @MacHut-coder 

The goal is to avoid hardcoded GPIOs as declared in [machines_def.h](https://github.com/iqrfsdk/clibspi/blob/master/include/machines_def.h)

It shall be possible via interface [spi_iqrf.h](https://github.com/iqrfsdk/clibspi/blob/master/include/spi_iqrf.h) to set these GPIOs e.g. via function `SPI_IQRF_DECLSPEC int spi_iqrf_init(const char *dev);` or rather by a new additional function. The GPIOs can be passed  as members of a structure. There could be predefined structures for known HW, e.g. KON-RASP-01 (could be default value). 

Verify HW risks in case of wrong configuration. Is it safe from HW POV? If not is it possible handle it somehow (warning, blocking wrong cfg wit error result of init fce, ...)

**Comment by fmikulu** [comment]
Implemented via 21336a1cb8296f9f7a655aea79e087613ef6d7a5
